// ============================================================
// EQUIPMENT CATALOG — danh mục thiết bị khoan (song ngữ)
// Dùng cho module Xuất/Nhập thiết bị (Equipment Check In/Check Out).
// ============================================================
export const EQUIPMENT_CATEGORIES = [
  { id: "main", vi: "Thiết bị chính", en: "Main Equipment" },
  { id: "spare", vi: "Phụ tùng máy khoan", en: "Drilling Machine Spare Parts" },
  { id: "tools", vi: "Dụng cụ khoan", en: "Drilling Tools" },
  { id: "general", vi: "Thiết bị chung", en: "General Equipment" },
  { id: "sampling", vi: "Lấy mẫu & vật tư tiêu hao", en: "Sampling & Consumables" },
  { id: "ppe", vi: "Bảo hộ lao động", en: "PPE" },
  { id: "other", vi: "Khác", en: "Other" },
];

export const EQUIPMENT_CATALOG = [
  { id: "drilling_machine", vi: "Máy khoan", en: "Drilling Machine", cat: "main", specs: ["Vàng - 5 số/Yellow – 5 Speed", "Đỏ - 5 số/Red – 5 Speed", "Cam - 5 số/Orange – 5 Speed"], custom: false },
  { id: "main_drilling_rod", vi: "Cần khoan chính", en: "Main Drilling Rod", cat: "main", specs: null, custom: false },
  { id: "drilling_rod", vi: "Cần khoan", en: "Drilling Rod", cat: "main", specs: ["4.6 m", "3.2 m", "2.3 m", "1.7 m", "1.0 m"], custom: false },
  { id: "spt_hammer", vi: "Búa SPT", en: "SPT Hammer", cat: "main", specs: null, custom: false },
  { id: "spt_tube", vi: "Ống SPT", en: "SPT Tube", cat: "main", specs: null, custom: false },
  { id: "spt_head", vi: "Đầu SPT", en: "SPT Head", cat: "main", specs: null, custom: false },
  { id: "soil_sampling_tube", vi: "Ống lấy mẫu đất", en: "Soil Sampling Tube", cat: "main", specs: ["Ø91 mm × 0.7 m", "Ø91 mm × 2 m", "Ø91 mm × 3 m", "Ø110 mm × 0.7 m", "Ø110 mm × 2 m", "Ø110 mm × 3 m", "Ø130 mm × 0.7 m", "Ø130 mm × 2 m", "Ø130 mm × 3 m", "Ø200 mm × 0.7 m", "Ø200 mm × 2 m"], custom: false },
  { id: "drilling_tower_foot", vi: "Chân tháp khoan", en: "Drilling Tower Foot", cat: "main", specs: null, custom: false },
  { id: "casing_pipe", vi: "Ống chống", en: "Casing Pipe", cat: "main", specs: ["Ø91 mm × 0 m", "Ø91 mm × 1 m", "Ø91 mm × 2 m", "Ø91 mm × 3 m", "Ø91 mm × 4 m", "Ø91 mm × 5 m", "Ø91 mm × 6 m", "Ø91 mm × 7 m", "Ø91 mm × 8 m", "Ø91 mm × 9 m", "Ø91 mm × 10 m", "Ø91 mm × 20 m", "Ø91 mm × 30 m", "Ø110 mm × 0 m", "Ø110 mm × 1 m", "Ø110 mm × 2 m", "Ø110 mm × 3 m", "Ø110 mm × 4 m", "Ø110 mm × 5 m", "Ø110 mm × 6 m", "Ø110 mm × 7 m", "Ø110 mm × 8 m", "Ø110 mm × 9 m", "Ø110 mm × 10 m", "Ø110 mm × 20 m", "Ø110 mm × 30 m", "Ø130 mm × 0 m", "Ø130 mm × 1 m", "Ø130 mm × 2 m", "Ø130 mm × 3 m", "Ø130 mm × 4 m", "Ø130 mm × 5 m", "Ø130 mm × 6 m", "Ø130 mm × 7 m", "Ø130 mm × 8 m", "Ø130 mm × 9 m", "Ø130 mm × 10 m", "Ø130 mm × 20 m", "Ø130 mm × 30 m"], custom: false },
  { id: "pipe_connector", vi: "Đầu nối ống", en: "Pipe Connector", cat: "main", specs: ["Ø91 mm", "Ø110 mm", "Ø130 mm", "Ø200 mm"], custom: false },
  { id: "clay_coring_bit", vi: "Mũi khoan lấy mẫu sét", en: "Clay Coring Bit", cat: "main", specs: ["Ø73 mm", "Ø91 mm", "Ø110 mm", "Ø130 mm", "Ø150 mm", "Ø200 mm"], custom: false },
  { id: "soil_coring_bit", vi: "Mũi khoan lấy mẫu đất", en: "Soil Coring Bit", cat: "main", specs: ["Ø73 mm", "Ø91 mm", "Ø110 mm", "Ø130 mm", "Ø150 mm", "Ø200 mm"], custom: false },
  { id: "rock_vertical_coring_bit", vi: "Mũi khoan lấy mẫu đá đứng", en: "Rock Vertical Coring Bit", cat: "main", specs: ["Ø73 mm", "Ø91 mm", "Ø110 mm", "Ø130 mm", "Ø150 mm", "Ø200 mm"], custom: false },
  { id: "rock_horizontal_coring_bit", vi: "Mũi khoan lấy mẫu đá ngang", en: "Rock Horizontal Coring Bit", cat: "main", specs: ["Ø73 mm", "Ø91 mm", "Ø110 mm", "Ø130 mm", "Ø150 mm", "Ø200 mm"], custom: false },
  { id: "clutch_disc", vi: "Lá côn", en: "Clutch Disc", cat: "spare", specs: null, custom: false },
  { id: "clutch_bolts", vi: "Bu lông côn", en: "Clutch Bolts", cat: "spare", specs: null, custom: false },
  { id: "pump_cylinder", vi: "Xi lanh bơm", en: "Pump Cylinder", cat: "spare", specs: null, custom: false },
  { id: "pump_steering_rod", vi: "Ty điều khiển bơm", en: "Pump Steering Rod", cat: "spare", specs: null, custom: false },
  { id: "pump_cup", vi: "Cúp bơm", en: "Pump Cup", cat: "spare", specs: null, custom: false },
  { id: "back_pump_cover", vi: "Nắp sau bơm", en: "Back Pump Cover", cat: "spare", specs: null, custom: false },
  { id: "top_pump_cover", vi: "Nắp trên bơm", en: "Top Pump Cover", cat: "spare", specs: null, custom: false },
  { id: "main_rod_reinforcement_steel", vi: "Thép gia cường cần khoan chính", en: "Main Rod Reinforcement Steel", cat: "spare", specs: null, custom: false },
  { id: "brass_gear", vi: "Bánh răng đồng", en: "Brass Gear", cat: "spare", specs: null, custom: false },
  { id: "three_jaw_gear", vi: "Bánh răng ba chấu", en: "Three-Jaw Gear", cat: "spare", specs: null, custom: false },
  { id: "pump_rubber_seal", vi: "Phớt cao su bơm", en: "Pump Rubber Seal", cat: "spare", specs: null, custom: false },
  { id: "rubber_oring_pump", vi: "Gioăng O-ring cao su cho bơm", en: "Rubber O-ring for Pump", cat: "spare", specs: null, custom: false },
  { id: "rubber_oring_main_rod", vi: "Gioăng O-ring cao su cho cần khoan chính", en: "Rubber O-ring for Main Rod", cat: "spare", specs: null, custom: false },
  { id: "rubber_oring_steering_rod", vi: "Gioăng O-ring cao su cho ty điều khiển bơm", en: "Rubber O-ring for Pump Steering Rod", cat: "spare", specs: null, custom: false },
  { id: "wrench", vi: "Cờ lê", en: "Wrench", cat: "tools", specs: ["Ø91 mm", "Ø110 mm", "Ø130 mm"], custom: false },
  { id: "chain_wrench", vi: "Cờ lê xích", en: "Chain Wrench", cat: "tools", specs: ["Ø91 mm", "Ø110 mm", "Ø130 mm"], custom: false },
  { id: "rod_opener", vi: "Dụng cụ mở cần khoan", en: "Rod Opener", cat: "tools", specs: null, custom: false },
  { id: "rod_keeper", vi: "Dụng cụ giữ cần khoan", en: "Rod Keeper", cat: "tools", specs: null, custom: false },
  { id: "rod_lifter_1", vi: "Bộ nâng cần khoan 1", en: "Rod Lifter 1", cat: "tools", specs: null, custom: false },
  { id: "rod_lifter_2", vi: "Bộ nâng cần khoan 2", en: "Rod Lifter 2", cat: "tools", specs: null, custom: false },
  { id: "pulley", vi: "Ròng rọc", en: "Pulley", cat: "tools", specs: null, custom: false },
  { id: "tower_bolt", vi: "Bu lông tháp khoan", en: "Tower's Bolt", cat: "tools", specs: null, custom: false },
  { id: "hand_crank", vi: "Tay quay", en: "Hand Crank", cat: "tools", specs: null, custom: false },
  { id: "pump_hose", vi: "Ống bơm", en: "Pump Hose", cat: "tools", specs: null, custom: false },
  { id: "luppe", vi: "Van Luppe", en: "Luppe", cat: "tools", specs: null, custom: false },
  { id: "pipe_wrench", vi: "Mỏ lết ống", en: "Pipe Wrench", cat: "tools", specs: null, custom: false },
  { id: "drum", vi: "Thùng phuy", en: "Drum", cat: "general", specs: null, custom: false },
  { id: "can_30l", vi: "Can 30L", en: "Can 30L", cat: "general", specs: null, custom: false },
  { id: "water_pipe", vi: "Ống nước", en: "Water Pipe", cat: "general", specs: null, custom: false },
  { id: "spade", vi: "Xẻng", en: "Spade", cat: "general", specs: null, custom: false },
  { id: "hoe", vi: "Cuốc", en: "Hoe", cat: "general", specs: null, custom: false },
  { id: "crowbar", vi: "Xà beng", en: "Crowbar", cat: "general", specs: null, custom: false },
  { id: "anchor", vi: "Neo", en: "Anchor", cat: "general", specs: null, custom: false },
  { id: "pipe_clamp", vi: "Kẹp ống", en: "Pipe Clamp", cat: "general", specs: null, custom: false },
  { id: "rope", vi: "Dây", en: "Rope", cat: "general", specs: null, custom: false },
  { id: "canvas", vi: "Bạt", en: "Canvas", cat: "general", specs: null, custom: false },
  { id: "generator", vi: "Máy phát điện", en: "Generator", cat: "general", specs: null, custom: false },
  { id: "pump", vi: "Máy bơm", en: "Pump", cat: "general", specs: null, custom: false },
  { id: "sample_pvc_tube", vi: "Ống PVC đựng mẫu", en: "Sample PVC Tube", cat: "sampling", specs: null, custom: false },
  { id: "sample_box", vi: "Thùng mẫu", en: "Sample Box", cat: "sampling", specs: null, custom: false },
  { id: "clear_tape", vi: "Băng keo trong", en: "Clear Tape", cat: "sampling", specs: null, custom: false },
  { id: "yellow_tape", vi: "Băng keo vàng", en: "Yellow Tape", cat: "sampling", specs: null, custom: false },
  { id: "sack", vi: "Bao tải", en: "Sack", cat: "sampling", specs: null, custom: false },
  { id: "safety_vest", vi: "Áo phản quang", en: "Safety Vest", cat: "ppe", specs: null, custom: false },
  { id: "life_jacket", vi: "Áo phao", en: "Life Jacket", cat: "ppe", specs: null, custom: false },
  { id: "safety_helmet", vi: "Mũ bảo hộ", en: "Safety Helmet", cat: "ppe", specs: null, custom: false },
  { id: "black_rubber_boots", vi: "Ủng cao su đen", en: "Black Rubber Boots", cat: "ppe", specs: null, custom: false },
  { id: "yellow_rubber_boots", vi: "Ủng cao su vàng có mũi thép", en: "Yellow Rubber Boots with Steel Toe", cat: "ppe", specs: null, custom: false },
  { id: "tool_box", vi: "Thùng dụng cụ", en: "Tool Box", cat: "other", specs: null, custom: false },
  { id: "bentonite", vi: "Bentonite", en: "Bentonite", cat: "other", specs: null, custom: false },
  { id: "other_equipment", vi: "Thiết bị khác", en: "Other Equipment", cat: "other", specs: null, custom: true },
];
